name: Rolling Release

on:
  push:
    branches: [ main ]

jobs:
  functional_performance_specification:
    name: Building Functional/Performance Specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the PDF
        run: |
          docker run -v ${{ github.workspace }}/functional_performance_specification:/data blang/latex make
      - name: Upload the PDF
        uses: actions/upload-artifact@v3
        with:
          name: functional-performance-specification.pdf
          path: ./functional-performance-specification/index.pdf

  release:
    name: Generating release
    runs-on: ubuntu-latest
    needs: functional_performance_specification
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: ${{ steps.date.outputs.date }}
      - name: Download Functional Performance Specification
        uses: actions/download-artifact@v3
        with:
          name: functional-performance-specification.pdf
      - name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          name: Build ${{ steps.date.outputs.date }}/${{ steps.buildnumber.outputs.build_number }}
          files: |
            functional-performance-specification.pdf